Sprint 6: Tests & Architecture
AndreiChenchik/practicum-ios-MovieQuiz pull request #7
Opened 2022-08-27 07:33 UTC by AndreiChenchik

* Implement testing
* Refactor architecture

2022-09-08 11:36 UTC, ABashkirova requested changes
Очень хорошая работа и жаль, что есть ошибки компиляции, в том числе из-за несовместимости новой версии Xcode полагаю.

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +}
Здесь все еще нужно указывать тип переменной, ошибка компиляции у тех ребят, что все еще на Xcode 13 :)

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if
не стоит ли вызвать метод super.viewDidLayoutSubviews?

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                let rating = Float(movie.rating) ?? 0
В прошлый раз про проверке упустила. Но однако замечу, что отсутствующий рейтинг, скорее признак не достаточности данных для квиза. Можно конечно и так обойтись, для тестового проекта не играет роли. Но я бы обработала фильтрацией загруженных фильмов.

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuizTests/DateTests.swift
> +        NSTimeZone.default = TimeZone.gmt
Можно ссылку где вы нашли `TimeZone.gmt`? У меня не компилируется

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuizTests/DateTests.swift
> +        NSTimeZone.default = TimeZone.gmt
предположу, что забыли расширение вроде этого `TimeZone(identifier: "GMT")!`

2022-09-08 11:36 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
> +		3820141F28BA417200DD05AC /* QuestionFactoryTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 3820141E28BA417200DD05AC /* QuestionFactoryTests.swift */; };
этого файла не достает. Проект не собирается и тесты не запускаются. 

Пожалуйста, исправьте и пришлите доработанный проект)

2022-09-09 10:51 UTC, AndreiChenchik commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +}
Блин, урок мне на будущее - не обновляться на новую macOS раньше времени
- новая os не поддерживает старый Xcode
- новый Xcode работает с swift 5.7
- откатить swift на 5.6 не получилось
- вот и возникают такие штуки

2022-09-09 10:53 UTC, AndreiChenchik commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if
Забыл, оно работает, а я и не трогаю :) Спасибо!

2022-09-09 11:14 UTC, AndreiChenchik commented on MovieQuiz/Services/QuestionFactory.swift
> +                let rating = Float(movie.rating) ?? 0
Согласен, идея хорошая, добавил, заодно перенес логику по приведению типов в codable модель

2022-09-09 11:17 UTC, AndreiChenchik commented on MovieQuiz.xcodeproj/project.pbxproj
> +		3820141F28BA417200DD05AC /* QuestionFactoryTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 3820141E28BA417200DD05AC /* QuestionFactoryTests.swift */; };
Ого, вот это поворот, не думал что он даже собираться не будет.

С этим тестом беда, я так и не понял как его делать, а наставник так мне никак и не пришлет инфу по тому как его можно было сделать :( в задачах его вроде тоже не было, так что просто удалил.

2022-09-09 11:25 UTC, AndreiChenchik commented on MovieQuizTests/DateTests.swift
> +        NSTimeZone.default = TimeZone.gmt
Хм, опять подводит свежий xCode
https://developer.apple.com/documentation/foundation/timezone/4059860-gmt

- Исправил таргет у тестов
- Изменил сигнатуру функции

2022-09-10 07:55 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +}
Ладно, со следующей недели не смогу уже на это ругаться 😄 но да, надо быть поснисходительнее к коллегам, кто еще не обновился)

2022-09-11 15:58 UTC, merged